---

connector:
  rpc:
    perun_url: "https://perun-dev.cesnet.cz/ba/rpc"
    perun_user: "user"
    perun_password: "pass"
    enabled: true
    request_timeout: 30000
    connect_timeout: 30000
    socket_timeout: 60000
    max_connections: 20
    max_connections_per_route: 18
  ldap:
    ldap_host: "perun-dev.cesnet.cz"
    ldap_user: "example user"
    ldap_password: "example password"
    timeout_secs: 100
    base_dn: "dc=perun,dc=cesnet,dc=cz"
    port: 636
    use_tls: true
    use_ssl: true
    allow_untrusted_ssl: false

attributes:
  path: /etc/perun/attributes.yml
  identifiers:
    facility: 'urn:perun:facility:attribute-def:def:entityID'

facade:
  default_idp: "https://idp.example.com/idp/"
  config_path:
    proxyuser: "/etc/perun/proxyuser-facade.yml"
    relying_party: "/etc/perun/relying-party-facade.yml"

security:
  basicauth:
    path: /etc/perun/api-auth.yml

server:
  port: 8080
  servlet:
    context-path: /proxyapi

management:
  info:
    git:
      enabled: false
    build:
      enabled: false
