---



connector:
  rpc:
    perun_url: "https://perun-dev.cesnet.cz/ba/rpc"
    perun_user: "user"
    perun_password: "pass"
    serializer: "json"
    enabled: true
    request_timeout: 30000
    connect_timeout: 30000
    socket_timeout: 60000
    max_connections: 20
    max_connections_per_route: 18
  ldap:
    ldap_hosts:
      - "ldaps://perun-dev.cesnet.cz:636"
      - "ldaps://perun-dev2.cesnet.cz:582"
    ldap_user: "example user"
    ldap_password: "example password"
    timeout: 60000
    connection_pool_size: 20
    base_dn: "dc=perun,dc=cesnet,dc=cz"
    use_tls: true

attributes:
  path: /etc/perun/attributes.yml
  identifiers:
    relying_party: "urn:perun:facility:attribute-def:def:entityID"
    login: "urn:perun:user:attribute-def:def:login-namespace:example"
    additional_identifiers: "urn:perun:user:attribute-def:def:additional-identifiers:example"

facade:
  config_path:
    proxyuser: "/etc/perun/proxyuser-facade.yml"
    relying_party: "/etc/perun/relying-party-facade.yml"

security:
  basicauth:
    path: /etc/perun/api-auth.yml

server:
  error:
    include-stacktrace: NEVER
  port: 8080
  servlet:
    context-path: /proxyapi

management:
  info:
    git:
      enabled: false
    build:
      enabled: false
